/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v2/artists': {
    get: {
      responses: {
        /** Success */
        200: {
          content: {
            'application/json': components['schemas']['ArtistWithCounts'][];
          };
        };
      };
    };
  };
  '/api/v3/artists': {
    get: {
      responses: {
        /** Success */
        200: {
          content: {
            'application/json': components['schemas']['ArtistWithCounts'][];
          };
        };
      };
    };
  };
  '/api/v2/artists/{artistIdOrSlug}': {
    get: {
      parameters: {
        path: {
          artistIdOrSlug: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            'application/json': components['schemas']['ArtistWithCounts'];
          };
        };
        /** Not Found */
        404: {
          content: {
            'application/json': components['schemas']['BooleanResponseEnvelope'];
          };
        };
      };
    };
  };
  '/api/v3/artists/{artistIdOrSlug}': {
    get: {
      parameters: {
        path: {
          artistIdOrSlug: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            'application/json': components['schemas']['ArtistWithCounts'];
          };
        };
        /** Not Found */
        404: {
          content: {
            'application/json': components['schemas']['BooleanResponseEnvelope'];
          };
        };
      };
    };
  };
  '/api/v3/artists/{artistUuid}/normalized': {
    get: {
      parameters: {
        path: {
          artistUuid: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            'application/json': components['schemas']['FullArtist'];
          };
        };
        /** Not Found */
        404: {
          content: {
            'application/json': components['schemas']['BooleanResponseEnvelope'];
          };
        };
      };
    };
  };
  '/api/v2/artists/{artistIdOrSlug}/eras': {
    get: {
      parameters: {
        path: {
          artistIdOrSlug: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            'application/json': components['schemas']['Era'][];
          };
        };
        /** Not Found */
        404: {
          content: {
            'application/json': components['schemas']['BooleanResponseEnvelope'];
          };
        };
      };
    };
  };
  '/api/v2/live/play': {
    post: {
      parameters: {
        query: {
          app_type?: string;
          track_id?: number;
          track_uuid?: string;
          user_uuid?: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            'application/json': components['schemas']['SourceTrackPlayResponseEnvelope'];
          };
        };
        /** Bad Request */
        400: unknown;
        /** Not Found */
        404: {
          content: {
            'application/json': components['schemas']['BooleanResponseEnvelope'];
          };
        };
      };
    };
  };
  '/api/v2/live/history': {
    get: {
      parameters: {
        query: {
          lastSeenId?: number;
          limit?: number;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            'application/json': components['schemas']['SourceTrackPlay'][];
          };
        };
      };
    };
  };
  '/api/v2/artists/{artistIdOrSlug}/shows/recently-added': {
    get: {
      parameters: {
        path: {
          artistIdOrSlug: string;
        };
        query: {
          limit?: number;
          previousDays?: number;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            'text/plain': components['schemas']['ShowWithArtist'][];
            'application/json': components['schemas']['ShowWithArtist'][];
            'text/json': components['schemas']['ShowWithArtist'][];
          };
        };
        /** Not Found */
        404: {
          content: {
            'text/plain': components['schemas']['BooleanResponseEnvelope'];
            'application/json': components['schemas']['BooleanResponseEnvelope'];
            'text/json': components['schemas']['BooleanResponseEnvelope'];
          };
        };
      };
    };
  };
  '/api/v2/artists/shows/recently-added': {
    get: {
      parameters: {
        query: {
          limit?: number;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            'text/plain': components['schemas']['ShowWithArtist'][];
            'application/json': components['schemas']['ShowWithArtist'][];
            'text/json': components['schemas']['ShowWithArtist'][];
          };
        };
        /** Not Found */
        404: {
          content: {
            'text/plain': components['schemas']['BooleanResponseEnvelope'];
            'application/json': components['schemas']['BooleanResponseEnvelope'];
            'text/json': components['schemas']['BooleanResponseEnvelope'];
          };
        };
      };
    };
  };
  '/api/v2/shows/recently-added': {
    get: {
      parameters: {
        query: {
          limit?: number;
          previousDays?: number;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            'text/plain': components['schemas']['ShowWithArtist'][];
            'application/json': components['schemas']['ShowWithArtist'][];
            'text/json': components['schemas']['ShowWithArtist'][];
          };
        };
        /** Not Found */
        404: {
          content: {
            'text/plain': components['schemas']['BooleanResponseEnvelope'];
            'application/json': components['schemas']['BooleanResponseEnvelope'];
            'text/json': components['schemas']['BooleanResponseEnvelope'];
          };
        };
      };
    };
  };
  '/api/v2/search': {
    get: {
      parameters: {
        query: {
          q?: string;
          artist_id?: number;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            'application/json': components['schemas']['SearchResults'];
          };
        };
      };
    };
  };
  '/api/v2/shows/today': {
    get: {
      responses: {
        /** Success */
        200: {
          content: {
            'application/json': components['schemas']['ShowWithArtist'][];
          };
        };
      };
    };
  };
  '/api/v2/shows/on-date': {
    get: {
      parameters: {
        query: {
          month?: number;
          day?: number;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            'application/json': components['schemas']['ShowWithArtist'][];
          };
        };
      };
    };
  };
  '/api/v2/shows/recently-performed': {
    get: {
      parameters: {
        query: {
          artistIds?: string[];
          shows?: number;
          days?: number;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            'application/json': components['schemas']['ShowWithArtist'][];
          };
        };
      };
    };
  };
  '/api/v2/shows/recently-updated': {
    get: {
      parameters: {
        query: {
          artistIds?: string[];
          shows?: number;
          days?: number;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            'application/json': components['schemas']['ShowWithArtist'][];
          };
        };
      };
    };
  };
  '/api/v2/artists/{artistIdOrSlug}/shows/today': {
    get: {
      parameters: {
        path: {
          artistIdOrSlug: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            'application/json': components['schemas']['ShowWithArtist'][];
          };
        };
        /** Not Found */
        404: {
          content: {
            'application/json': components['schemas']['BooleanResponseEnvelope'];
          };
        };
      };
    };
  };
  '/api/v2/artists/{artistIdOrSlug}/shows/recently-performed': {
    get: {
      parameters: {
        path: {
          artistIdOrSlug: string;
        };
        query: {
          shows?: number;
          days?: number;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            'application/json': components['schemas']['ShowWithArtist'][];
          };
        };
        /** Not Found */
        404: {
          content: {
            'application/json': components['schemas']['BooleanResponseEnvelope'];
          };
        };
      };
    };
  };
  '/api/v2/artists/{artistIdOrSlug}/shows/recently-updated': {
    get: {
      parameters: {
        path: {
          artistIdOrSlug: string;
        };
        query: {
          shows?: number;
          days?: number;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            'application/json': components['schemas']['ShowWithArtist'][];
          };
        };
        /** Not Found */
        404: {
          content: {
            'application/json': components['schemas']['BooleanResponseEnvelope'];
          };
        };
      };
    };
  };
  '/api/v2/artists/{artistIdOrSlug}/shows/on-date': {
    get: {
      parameters: {
        path: {
          artistIdOrSlug: string;
        };
        query: {
          month?: number;
          day?: number;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            'application/json': components['schemas']['ShowWithArtist'][];
          };
        };
      };
    };
  };
  '/api/v2/artists/{artistIdOrSlug}/shows/top': {
    get: {
      parameters: {
        path: {
          artistIdOrSlug: string;
        };
        query: {
          limit?: number;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            'application/json': components['schemas']['Show'][];
          };
        };
        /** Not Found */
        404: {
          content: {
            'application/json': components['schemas']['BooleanResponseEnvelope'];
          };
        };
      };
    };
  };
  '/api/v2/artists/{artistIdOrSlug}/shows/random': {
    get: {
      parameters: {
        path: {
          artistIdOrSlug: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            'application/json': components['schemas']['ShowWithSources'];
          };
        };
        /** Not Found */
        404: {
          content: {
            'application/json': components['schemas']['BooleanResponseEnvelope'];
          };
        };
      };
    };
  };
  '/api/v2/artists/{artistIdOrSlug}/shows/{showDate}': {
    get: {
      parameters: {
        path: {
          artistIdOrSlug: string;
          showDate: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            'application/json': components['schemas']['ShowWithSources'];
          };
        };
        /** Not Found */
        404: {
          content: {
            'application/json': components['schemas']['BooleanResponseEnvelope'];
          };
        };
      };
    };
  };
  '/api/v3/shows/{showUuid}': {
    get: {
      parameters: {
        path: {
          showUuid: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            'application/json': components['schemas']['ShowWithSources'];
          };
        };
        /** Not Found */
        404: {
          content: {
            'application/json': components['schemas']['BooleanResponseEnvelope'];
          };
        };
      };
    };
  };
  '/api/v2/artists/{artistIdOrSlug}/sources/{sourceId}/reviews': {
    get: {
      parameters: {
        path: {
          artistIdOrSlug: string;
          sourceId: number;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            'application/json': components['schemas']['SourceReview'][];
          };
        };
        /** Not Found */
        404: {
          content: {
            'application/json': components['schemas']['BooleanResponseEnvelope'];
          };
        };
      };
    };
  };
  '/api/v2/artists/{artistIdOrSlug}/songs': {
    get: {
      parameters: {
        path: {
          artistIdOrSlug: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            'application/json': components['schemas']['SetlistSongWithPlayCount'][];
          };
        };
        /** Not Found */
        404: {
          content: {
            'application/json': components['schemas']['BooleanResponseEnvelope'];
          };
        };
      };
    };
  };
  '/api/v2/artists/{artistIdOrSlug}/songs/{idAndSlug}': {
    get: {
      parameters: {
        path: {
          artistIdOrSlug: string;
          idAndSlug: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            'application/json': components['schemas']['SetlistSongWithShows'];
          };
        };
        /** Not Found */
        404: {
          content: {
            'application/json': components['schemas']['BooleanResponseEnvelope'];
          };
        };
      };
    };
  };
  '/api/v2/artists/{artistIdOrSlug}/tours': {
    get: {
      parameters: {
        path: {
          artistIdOrSlug: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            'application/json': components['schemas']['TourWithShowCount'][];
          };
        };
        /** Not Found */
        404: {
          content: {
            'application/json': components['schemas']['BooleanResponseEnvelope'];
          };
        };
      };
    };
  };
  '/api/v2/artists/{artistIdOrSlug}/tours/{idAndSlug}': {
    get: {
      parameters: {
        path: {
          artistIdOrSlug: string;
          idAndSlug: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            'application/json': components['schemas']['TourWithShows'];
          };
        };
        /** Not Found */
        404: {
          content: {
            'application/json': components['schemas']['BooleanResponseEnvelope'];
          };
        };
      };
    };
  };
  '/api/v2/artists/{artistIdOrSlug}/venues': {
    get: {
      parameters: {
        path: {
          artistIdOrSlug: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            'application/json': components['schemas']['VenueWithShowCount'][];
          };
        };
        /** Not Found */
        404: {
          content: {
            'application/json': components['schemas']['BooleanResponseEnvelope'];
          };
        };
      };
    };
  };
  '/api/v2/artists/{artistIdOrSlug}/venues/{idAndSlug}': {
    get: {
      parameters: {
        path: {
          artistIdOrSlug: string;
          idAndSlug: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            'application/json': components['schemas']['VenueWithShows'];
          };
        };
        /** Not Found */
        404: {
          content: {
            'application/json': components['schemas']['BooleanResponseEnvelope'];
          };
        };
      };
    };
  };
  '/api/v2/artists/{artistIdOrSlug}/years': {
    get: {
      parameters: {
        path: {
          artistIdOrSlug: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            'application/json': components['schemas']['Year'][];
          };
        };
        /** Not Found */
        404: {
          content: {
            'application/json': components['schemas']['BooleanResponseEnvelope'];
          };
        };
      };
    };
  };
  '/api/v3/artists/{artistIdOrSlug}/years': {
    get: {
      parameters: {
        path: {
          artistIdOrSlug: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            'application/json': components['schemas']['Year'][];
          };
        };
        /** Not Found */
        404: {
          content: {
            'application/json': components['schemas']['BooleanResponseEnvelope'];
          };
        };
      };
    };
  };
  '/api/v2/artists/{artistIdOrSlug}/years/{year}': {
    get: {
      parameters: {
        path: {
          artistIdOrSlug: string;
          year: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            'application/json': components['schemas']['YearWithShows'];
          };
        };
        /** Not Found */
        404: {
          content: {
            'application/json': components['schemas']['BooleanResponseEnvelope'];
          };
        };
      };
    };
  };
  '/api/v3/artists/{artistIdOrSlug}/years/{yearUuid}': {
    get: {
      parameters: {
        path: {
          artistIdOrSlug: string;
          yearUuid: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            'application/json': components['schemas']['YearWithShows'];
          };
        };
        /** Not Found */
        404: {
          content: {
            'application/json': components['schemas']['BooleanResponseEnvelope'];
          };
        };
      };
    };
  };
  '/api/v2/artists/{artistIdOrSlug}/years/{year}/{showDate}': {
    get: {
      parameters: {
        path: {
          artistIdOrSlug: string;
          year: string;
          showDate: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            'application/json': components['schemas']['ShowWithSources'];
          };
        };
        /** Not Found */
        404: {
          content: {
            'application/json': components['schemas']['BooleanResponseEnvelope'];
          };
        };
      };
    };
  };
}

export interface components {
  schemas: {
    /**
     * Format: int32
     * @enum {integer}
     */
    ApiErrorCode: 0 | 404;
    Artist: {
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
      musicbrainz_id: string;
      name: string;
      /** Format: int32 */
      featured: number;
      slug: string;
      sort_name: string;
      /** Format: uuid */
      uuid: string;
      features: components['schemas']['Features'];
      upstream_sources: components['schemas']['ArtistUpstreamSource'][];
    } & {
      id: unknown;
    };
    ArtistUpstreamSource: {
      /** Format: int32 */
      upstream_source_id: number;
      upstream_identifier?: string | null;
      /** Format: uuid */
      artist_uuid: string;
      upstream_source?: components['schemas']['UpstreamSource'];
    } & {
      artist_id: unknown;
    };
    ArtistWithCounts: {
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
      musicbrainz_id: string;
      name: string;
      /** Format: int32 */
      featured: number;
      slug: string;
      sort_name: string;
      /** Format: uuid */
      uuid: string;
      features: components['schemas']['Features'];
      upstream_sources: components['schemas']['ArtistUpstreamSource'][];
      /** Format: int32 */
      show_count: number;
      /** Format: int32 */
      source_count: number;
    } & {
      id: unknown;
    };
    BooleanResponseEnvelope: {
      success: boolean;
      error_code: components['schemas']['ApiErrorCode'];
      data: boolean;
    };
    Era: {
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
      /** Format: int32 */
      artist_id: number;
      /** Format: uuid */
      artist_uuid: string;
      /** Format: int32 */
      order: number;
      name: string;
    } & {
      id: unknown;
    };
    Features: {
      descriptions: boolean;
      eras: boolean;
      multiple_sources: boolean;
      reviews: boolean;
      ratings: boolean;
      tours: boolean;
      taper_notes: boolean;
      source_information: boolean;
      sets: boolean;
      per_show_venues: boolean;
      per_source_venues: boolean;
      venue_coords: boolean;
      songs: boolean;
      years: boolean;
      track_md5s: boolean;
      review_titles: boolean;
      jam_charts: boolean;
      setlist_data_incomplete: boolean;
      track_names: boolean;
      venue_past_names: boolean;
      reviews_have_ratings: boolean;
      track_durations: boolean;
      can_have_flac: boolean;
    } & {
      artist_id: unknown;
      id: unknown;
    };
    /**
     * Format: int32
     * @enum {integer}
     */
    FlacType: 0 | 1 | 2 | 3;
    FullArtist: {
      artist: components['schemas']['ArtistWithCounts'];
      venues: components['schemas']['VenueWithShowCount'][];
      songs: components['schemas']['SetlistSongWithPlayCount'][];
      tours: components['schemas']['TourWithShowCount'][];
      years: components['schemas']['Year'][];
      shows: components['schemas']['Show'][];
    };
    ImporterBase: {
      importerName?: string | null;
    };
    Link: {
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
      /** Format: int32 */
      source_id: number;
      /** Format: int32 */
      upstream_source_id: number;
      for_reviews: boolean;
      for_ratings: boolean;
      for_source: boolean;
      url: string;
      label: string;
    } & {
      id: unknown;
    };
    PlayedSourceTrack: {
      source: components['schemas']['SlimSourceWithShowVenueAndArtist'];
      track: components['schemas']['SourceTrack'];
    };
    SearchResults: {
      artists: components['schemas']['SlimArtist'][];
      shows: components['schemas']['ShowWithSlimArtist'][];
      songs: components['schemas']['SetlistSongWithSlimArtist'][];
      source: components['schemas']['SourceWithSlimArtist'][];
      tours: components['schemas']['TourWithSlimArtist'][];
      venues: components['schemas']['VenueWithSlimArtist'][];
    };
    SetlistSongWithPlayCount: {
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
      /** Format: uuid */
      artist_uuid: string;
      name: string;
      slug: string;
      upstream_identifier: string;
      sortName: string;
      /** Format: uuid */
      uuid: string;
      /** Format: int32 */
      shows_played_at: number;
    } & {
      artist_id: unknown;
      id: unknown;
    };
    SetlistSongWithShows: {
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
      /** Format: uuid */
      artist_uuid: string;
      name: string;
      slug: string;
      upstream_identifier: string;
      sortName: string;
      /** Format: uuid */
      uuid: string;
      shows: components['schemas']['Show'][];
    } & {
      artist_id: unknown;
      id: unknown;
    };
    SetlistSongWithSlimArtist: {
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
      /** Format: uuid */
      artist_uuid: string;
      name: string;
      slug: string;
      upstream_identifier: string;
      sortName: string;
      /** Format: uuid */
      uuid: string;
      /** Format: int32 */
      shows_played_at: number;
      slim_artist: components['schemas']['SlimArtist'];
    } & {
      artist_id: unknown;
      id: unknown;
    };
    Show: {
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
      /** Format: uuid */
      artist_uuid: string;
      venue?: components['schemas']['VenueWithShowCount'];
      /** Format: uuid */
      venue_uuid?: string | null;
      /** Format: uuid */
      tour_uuid?: string | null;
      tour?: components['schemas']['Tour'];
      /** Format: uuid */
      year_uuid: string;
      year?: components['schemas']['Year'];
      era?: components['schemas']['Era'];
      /** Format: date-time */
      date: string;
      /** Format: float */
      avg_rating: number;
      /** Format: float */
      avg_duration?: number | null;
      display_date: string;
      /** Format: date-time */
      most_recent_source_updated_at: string;
      has_soundboard_source: boolean;
      has_streamable_flac_source: boolean;
      /** Format: int32 */
      source_count: number;
      /** Format: uuid */
      uuid: string;
    } & {
      artist_id: unknown;
      id: unknown;
    };
    ShowWithArtist: {
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
      /** Format: uuid */
      artist_uuid: string;
      venue?: components['schemas']['VenueWithShowCount'];
      /** Format: uuid */
      venue_uuid?: string | null;
      /** Format: uuid */
      tour_uuid?: string | null;
      tour?: components['schemas']['Tour'];
      /** Format: uuid */
      year_uuid?: string;
      year?: components['schemas']['Year'];
      era?: components['schemas']['Era'];
      /** Format: date-time */
      date: string;
      /** Format: float */
      avg_rating: number;
      /** Format: float */
      avg_duration?: number | null;
      display_date: string;
      /** Format: date-time */
      most_recent_source_updated_at: string;
      has_soundboard_source: boolean;
      has_streamable_flac_source: boolean;
      /** Format: int32 */
      source_count: number;
      /** Format: uuid */
      uuid: string;
      artist: components['schemas']['Artist'];
    } & {
      artist_id: unknown;
      id: unknown;
    };
    ShowWithSlimArtist: {
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
      /** Format: uuid */
      artist_uuid: string;
      venue?: components['schemas']['VenueWithShowCount'];
      /** Format: uuid */
      venue_uuid?: string | null;
      /** Format: uuid */
      tour_uuid?: string | null;
      tour?: components['schemas']['Tour'];
      /** Format: uuid */
      year_uuid?: string;
      year?: components['schemas']['Year'];
      era?: components['schemas']['Era'];
      /** Format: date-time */
      date: string;
      /** Format: float */
      avg_rating: number;
      /** Format: float */
      avg_duration?: number | null;
      display_date: string;
      /** Format: date-time */
      most_recent_source_updated_at: string;
      has_soundboard_source: boolean;
      has_streamable_flac_source: boolean;
      /** Format: int32 */
      source_count: number;
      /** Format: uuid */
      uuid: string;
      slim_artist: components['schemas']['SlimArtist'];
    } & {
      artist_id: unknown;
      id: unknown;
    };
    ShowWithSources: {
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
      /** Format: uuid */
      artist_uuid: string;
      venue?: components['schemas']['VenueWithShowCount'];
      /** Format: uuid */
      venue_uuid?: string | null;
      /** Format: uuid */
      tour_uuid?: string | null;
      tour?: components['schemas']['Tour'];
      /** Format: uuid */
      year_uuid?: string;
      year?: components['schemas']['Year'];
      era?: components['schemas']['Era'];
      /** Format: date-time */
      date: string;
      /** Format: float */
      avg_rating: number;
      /** Format: float */
      avg_duration?: number | null;
      display_date: string;
      /** Format: date-time */
      most_recent_source_updated_at: string;
      has_soundboard_source: boolean;
      has_streamable_flac_source: boolean;
      /** Format: int32 */
      source_count: number;
      /** Format: uuid */
      uuid: string;
      sources: components['schemas']['SourceFull'][];
    } & {
      artist_id: unknown;
      id: unknown;
    };
    SlimArtist: {
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
      musicbrainz_id: string;
      name: string;
      /** Format: int32 */
      featured: number;
      slug: string;
      sort_name: string;
      /** Format: uuid */
      uuid: string;
    } & {
      id: unknown;
    };
    SlimArtistWithFeatures: {
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
      musicbrainz_id: string;
      name: string;
      /** Format: int32 */
      featured: number;
      slug: string;
      sort_name: string;
      /** Format: uuid */
      uuid: string;
      features: components['schemas']['Features'];
    } & {
      id: unknown;
    };
    SlimSourceWithShowVenueAndArtist: {
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
      /** Format: uuid */
      artist_uuid: string;
      /** Format: uuid */
      venue_uuid: string;
      venue?: components['schemas']['Venue'];
      display_date: string;
      is_soundboard: boolean;
      is_remaster: boolean;
      has_jamcharts: boolean;
      /** Format: double */
      avg_rating: number;
      /** Format: int32 */
      num_reviews: number;
      /** Format: int32 */
      num_ratings?: number | null;
      /** Format: double */
      avg_rating_weighted: number;
      /** Format: double */
      duration?: number;
      upstream_identifier: string;
      /** Format: uuid */
      uuid: string;
      /** Format: uuid */
      show_uuid: string;
      show?: components['schemas']['Show'];
      artist: components['schemas']['SlimArtistWithFeatures'];
    } & {
      artist_id: unknown;
      id: unknown;
      show_id: unknown;
      venue_id: unknown;
    };
    Song: {
      created_at: string;
      updated_at: string;
      artist_uuid: string;
      name: string;
      slug: string;
      upstream_identifier: string;
      sortName: string;
      uuid: string;
      shows_played_at?: number;
    } & {
      id: unknown;
      artist_id: unknown;
    };
    SourceFull: {
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
      /** Format: uuid */
      artist_uuid: string;
      /** Format: uuid */
      venue_uuid: string;
      venue?: components['schemas']['Venue'];
      display_date: string;
      is_soundboard: boolean;
      is_remaster: boolean;
      has_jamcharts: boolean;
      /** Format: double */
      avg_rating: number;
      /** Format: int32 */
      num_reviews: number;
      /** Format: int32 */
      num_ratings?: number | null;
      /** Format: double */
      avg_rating_weighted: number;
      /** Format: double */
      duration?: number;
      upstream_identifier: string;
      /** Format: uuid */
      uuid: string;
      /** Format: uuid */
      show_uuid: string;
      show?: components['schemas']['Show'];
      description: string;
      taper_notes: string;
      source: string;
      taper: string;
      transferrer: string;
      lineage: string;
      flac_type: components['schemas']['FlacType'];
      /** Format: int32 */
      review_count: number;
      sets: components['schemas']['SourceSet'][];
      links: components['schemas']['Link'][];
    } & {
      artist_id: unknown;
      id: unknown;
      show_id: unknown;
      venue_id: unknown;
    };
    SourceReview: {
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
      /** Format: int32 */
      source_id: number;
      /** Format: int32 */
      rating?: number | null;
      title?: string | null;
      review: string;
      author?: string | null;
      /** Format: uuid */
      uuid: string;
    } & {
      id: unknown;
    };
    SourceSet: {
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
      /** Format: uuid */
      source_uuid: string;
      /** Format: uuid */
      artist_uuid: string;
      /** Format: uuid */
      uuid: string;
      /** Format: int32 */
      index: number;
      is_encore: boolean;
      name: string;
      tracks: components['schemas']['SourceTrack'][];
    } & {
      artist_id: unknown;
      id: unknown;
      source_id: unknown;
    };
    SourceTrack: {
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
      /** Format: uuid */
      source_uuid: string;
      /** Format: uuid */
      source_set_uuid: string;
      /** Format: uuid */
      artist_uuid: string;
      /** Format: int32 */
      track_position: number;
      /** Format: int32 */
      duration?: number | null;
      title: string;
      slug: string;
      mp3_url?: string | null;
      mp3_md5?: string | null;
      flac_url?: string | null;
      flac_md5?: string | null;
      /** Format: uuid */
      uuid: string;
    } & {
      artist_id: unknown;
      id: unknown;
      source_id: unknown;
      source_set_id: unknown;
    };
    SourceTrackPlay: {
      /** Format: int32 */
      id: number;
      /** Format: date-time */
      created_at: string;
      /** Format: uuid */
      source_track_uuid: string;
      /** Format: uuid */
      user_uuid: string;
      app_type: components['schemas']['SourceTrackPlayAppType'];
      app_type_description: components['schemas']['SourceTrackPlayAppType'];
      track?: components['schemas']['PlayedSourceTrack'];
    };
    /**
     * Format: int32
     * @enum {integer}
     */
    SourceTrackPlayAppType: 0 | 1 | 2 | 3;
    SourceTrackPlayResponseEnvelope: {
      success: boolean;
      error_code: components['schemas']['ApiErrorCode'];
      data: components['schemas']['SourceTrackPlay'];
    };
    SourceWithSlimArtist: {
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
      /** Format: uuid */
      artist_uuid: string;
      /** Format: uuid */
      venue_uuid: string;
      venue?: components['schemas']['Venue'];
      display_date: string;
      is_soundboard: boolean;
      is_remaster: boolean;
      has_jamcharts: boolean;
      /** Format: double */
      avg_rating: number;
      /** Format: int32 */
      num_reviews: number;
      /** Format: int32 */
      num_ratings?: number | null;
      /** Format: double */
      avg_rating_weighted: number;
      /** Format: double */
      duration?: number;
      upstream_identifier: string;
      /** Format: uuid */
      uuid: string;
      /** Format: uuid */
      show_uuid: string;
      show?: components['schemas']['Show'];
      description: string;
      taper_notes: string;
      source: string;
      taper: string;
      transferrer: string;
      lineage: string;
      flac_type: components['schemas']['FlacType'];
      slim_artist: components['schemas']['SlimArtist'];
    } & {
      artist_id: unknown;
      id: unknown;
      show_id: unknown;
      venue_id: unknown;
    };
    Tour: {
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
      /** Format: uuid */
      artist_uuid: string;
      /** Format: date-time */
      start_date: string;
      /** Format: date-time */
      end_date: string;
      name: string;
      slug: string;
      upstream_identifier: string;
      /** Format: uuid */
      uuid: string;
    } & {
      artist_id: unknown;
      id: unknown;
    };
    TourWithShowCount: {
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
      /** Format: uuid */
      artist_uuid: string;
      /** Format: date-time */
      start_date: string;
      /** Format: date-time */
      end_date: string;
      name: string;
      slug: string;
      upstream_identifier: string;
      /** Format: uuid */
      uuid: string;
      /** Format: int32 */
      shows_on_tour?: number;
    } & {
      artist_id: unknown;
      id: unknown;
    };
    TourWithShows: {
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
      /** Format: uuid */
      artist_uuid: string;
      /** Format: date-time */
      start_date: string;
      /** Format: date-time */
      end_date: string;
      name: string;
      slug: string;
      upstream_identifier: string;
      /** Format: uuid */
      uuid: string;
      shows: components['schemas']['Show'][];
    } & {
      artist_id: unknown;
      id: unknown;
    };
    TourWithSlimArtist: {
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
      /** Format: uuid */
      artist_uuid: string;
      /** Format: date-time */
      start_date: string;
      /** Format: date-time */
      end_date: string;
      name: string;
      slug: string;
      upstream_identifier: string;
      /** Format: uuid */
      uuid: string;
      slim_artist: components['schemas']['SlimArtist'];
    } & {
      artist_id: unknown;
      id: unknown;
    };
    UpstreamSource: {
      name: string;
      url: string;
      description: string;
      credit_line: string;
      importer?: components['schemas']['ImporterBase'];
    } & {
      id: unknown;
    };
    Venue: {
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
      /** Format: uuid */
      artist_uuid: string;
      /** Format: double */
      latitude?: number | null;
      /** Format: double */
      longitude?: number | null;
      name: string;
      location: string;
      upstream_identifier: string;
      slug: string;
      past_names?: string | null;
      sortName: string;
      /** Format: uuid */
      uuid: string;
    } & {
      artist_id: unknown;
      id: unknown;
    };
    VenueWithShowCount: {
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
      /** Format: uuid */
      artist_uuid: string;
      /** Format: double */
      latitude?: number | null;
      /** Format: double */
      longitude?: number | null;
      name: string;
      location: string;
      upstream_identifier: string;
      slug: string;
      past_names?: string | null;
      sortName: string;
      /** Format: uuid */
      uuid: string;
      /** Format: int32 */
      shows_at_venue: number;
    } & {
      artist_id: unknown;
      id: unknown;
    };
    VenueWithShows: {
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
      /** Format: uuid */
      artist_uuid: string;
      /** Format: double */
      latitude?: number | null;
      /** Format: double */
      longitude?: number | null;
      name: string;
      location: string;
      upstream_identifier: string;
      slug: string;
      past_names?: string | null;
      sortName: string;
      /** Format: uuid */
      uuid: string;
      /** Format: int32 */
      shows_at_venue: number;
      shows: components['schemas']['Show'][];
    } & {
      artist_id: unknown;
      id: unknown;
    };
    VenueWithSlimArtist: {
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
      /** Format: uuid */
      artist_uuid: string;
      /** Format: double */
      latitude?: number | null;
      /** Format: double */
      longitude?: number | null;
      name: string;
      location: string;
      upstream_identifier: string;
      slug: string;
      past_names?: string | null;
      sortName: string;
      /** Format: uuid */
      uuid: string;
      slim_artist: components['schemas']['SlimArtist'];
    } & {
      artist_id: unknown;
      id: unknown;
    };
    Year: {
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
      /** Format: int32 */
      show_count: number;
      /** Format: int32 */
      source_count: number;
      /** Format: int32 */
      duration?: number | null;
      /** Format: float */
      avg_duration?: number | null;
      /** Format: float */
      avg_rating: number;
      year: string;
      /** Format: uuid */
      artist_uuid: string;
      /** Format: uuid */
      uuid: string;
    } & {
      artist_id: unknown;
      id: unknown;
    };
    YearWithShows: {
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
      /** Format: int32 */
      show_count: number;
      /** Format: int32 */
      source_count: number;
      /** Format: int32 */
      duration?: number | null;
      /** Format: float */
      avg_duration?: number | null;
      /** Format: float */
      avg_rating: number;
      year: string;
      /** Format: uuid */
      artist_uuid: string;
      /** Format: uuid */
      uuid: string;
      shows: components['schemas']['Show'][];
    } & {
      artist_id: unknown;
      id: unknown;
    };
  };
}

export interface operations {}

export interface external {}
