// tslint:disable
/**
 * Relisten API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ApiErrorCode {
    NUMBER_0 = 0,
    NUMBER_404 = 404
}

export function ApiErrorCodeFromJSON(json: any): ApiErrorCode {
    return json as ApiErrorCode;
}

export function ApiErrorCodeToJSON(value?: ApiErrorCode): any {
    return value as any;
}

