/* tslint:disable */
/* eslint-disable */
/**
 * Relisten API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    ArtistUpstreamSource,
    ArtistUpstreamSourceFromJSON,
    ArtistUpstreamSourceToJSON,
    Features,
    FeaturesFromJSON,
    FeaturesToJSON,
} from './';

/**
 *
 * @export
 * @interface ArtistWithCounts
 */
export interface ArtistWithCounts {
    /**
     *
     * @type {number}
     * @memberof ArtistWithCounts
     */
    showCount: number;
    /**
     *
     * @type {number}
     * @memberof ArtistWithCounts
     */
    sourceCount: number;
    /**
     *
     * @type {Array<ArtistUpstreamSource>}
     * @memberof ArtistWithCounts
     */
    upstreamSources: Array<ArtistUpstreamSource> | null;
    /**
     *
     * @type {Features}
     * @memberof ArtistWithCounts
     */
    features: Features;
    /**
     *
     * @type {string}
     * @memberof ArtistWithCounts
     */
    musicbrainzId: string | null;
    /**
     *
     * @type {string}
     * @memberof ArtistWithCounts
     */
    name: string | null;
    /**
     *
     * @type {number}
     * @memberof ArtistWithCounts
     */
    featured: number;
    /**
     *
     * @type {string}
     * @memberof ArtistWithCounts
     */
    slug: string | null;
    /**
     *
     * @type {string}
     * @memberof ArtistWithCounts
     */
    sortName: string | null;
    /**
     *
     * @type {string}
     * @memberof ArtistWithCounts
     */
    uuid: string;
    /**
     *
     * @type {number}
     * @memberof ArtistWithCounts
     */
    id: number;
    /**
     *
     * @type {Date}
     * @memberof ArtistWithCounts
     */
    createdAt: Date;
    /**
     *
     * @type {Date}
     * @memberof ArtistWithCounts
     */
    updatedAt: Date;
}

export function ArtistWithCountsFromJSON(json: any): ArtistWithCounts {
    return ArtistWithCountsFromJSONTyped(json, false);
}

export function ArtistWithCountsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArtistWithCounts {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'showCount': json['show_count'],
        'sourceCount': json['source_count'],
        'upstreamSources': (json['upstream_sources'] === null ? null : (json['upstream_sources'] as Array<any>).map(ArtistUpstreamSourceFromJSON)),
        'features': FeaturesFromJSON(json['features']),
        'musicbrainzId': json['musicbrainz_id'],
        'name': json['name'],
        'featured': json['featured'],
        'slug': json['slug'],
        'sortName': json['sort_name'],
        'uuid': json['uuid'],
        'id': json['id'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function ArtistWithCountsToJSON(value?: ArtistWithCounts | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'show_count': value.showCount,
        'source_count': value.sourceCount,
        'upstream_sources': (value.upstreamSources === null ? null : (value.upstreamSources as Array<any>).map(ArtistUpstreamSourceToJSON)),
        'features': FeaturesToJSON(value.features),
        'musicbrainz_id': value.musicbrainzId,
        'name': value.name,
        'featured': value.featured,
        'slug': value.slug,
        'sort_name': value.sortName,
        'uuid': value.uuid,
        'id': value.id,
        'created_at': (value.createdAt.toISOString()),
        'updated_at': (value.updatedAt.toISOString()),
    };
}


