/* tslint:disable */
/* eslint-disable */
/**
 * Relisten API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ArtistUpstreamSource,
    ArtistUpstreamSourceFromJSON,
    ArtistUpstreamSourceFromJSONTyped,
    ArtistUpstreamSourceToJSON,
    Features,
    FeaturesFromJSON,
    FeaturesFromJSONTyped,
    FeaturesToJSON,
} from './';

/**
 * 
 * @export
 * @interface Artist
 */
export interface Artist {
    /**
     * 
     * @type {Array<ArtistUpstreamSource>}
     * @memberof Artist
     */
    upstreamSources: Array<ArtistUpstreamSource> | null;
    /**
     * 
     * @type {Features}
     * @memberof Artist
     */
    features: Features;
    /**
     * 
     * @type {string}
     * @memberof Artist
     */
    musicbrainzId: string | null;
    /**
     * 
     * @type {string}
     * @memberof Artist
     */
    name: string | null;
    /**
     * 
     * @type {number}
     * @memberof Artist
     */
    featured: number;
    /**
     * 
     * @type {string}
     * @memberof Artist
     */
    slug: string | null;
    /**
     * 
     * @type {string}
     * @memberof Artist
     */
    sortName: string | null;
    /**
     * 
     * @type {string}
     * @memberof Artist
     */
    uuid: string;
    /**
     * 
     * @type {number}
     * @memberof Artist
     */
    id: number;
    /**
     * 
     * @type {Date}
     * @memberof Artist
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Artist
     */
    updatedAt: Date;
}

export function ArtistFromJSON(json: any): Artist {
    return ArtistFromJSONTyped(json, false);
}

export function ArtistFromJSONTyped(json: any, ignoreDiscriminator: boolean): Artist {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'upstreamSources': (json['upstream_sources'] === null ? null : (json['upstream_sources'] as Array<any>).map(ArtistUpstreamSourceFromJSON)),
        'features': FeaturesFromJSON(json['features']),
        'musicbrainzId': json['musicbrainz_id'],
        'name': json['name'],
        'featured': json['featured'],
        'slug': json['slug'],
        'sortName': json['sort_name'],
        'uuid': json['uuid'],
        'id': json['id'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function ArtistToJSON(value?: Artist | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'upstream_sources': (value.upstreamSources === null ? null : (value.upstreamSources as Array<any>).map(ArtistUpstreamSourceToJSON)),
        'features': FeaturesToJSON(value.features),
        'musicbrainz_id': value.musicbrainzId,
        'name': value.name,
        'featured': value.featured,
        'slug': value.slug,
        'sort_name': value.sortName,
        'uuid': value.uuid,
        'id': value.id,
        'created_at': (value.createdAt.toISOString()),
        'updated_at': (value.updatedAt.toISOString()),
    };
}


