/* tslint:disable */
/* eslint-disable */
/**
 * Relisten API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    UpstreamSource,
    UpstreamSourceFromJSON,
    UpstreamSourceFromJSONTyped,
    UpstreamSourceToJSON,
} from './';

/**
 * 
 * @export
 * @interface ArtistUpstreamSource
 */
export interface ArtistUpstreamSource {
    /**
     * 
     * @type {number}
     * @memberof ArtistUpstreamSource
     */
    artistId: number;
    /**
     * 
     * @type {UpstreamSource}
     * @memberof ArtistUpstreamSource
     */
    upstreamSource?: UpstreamSource;
    /**
     * 
     * @type {number}
     * @memberof ArtistUpstreamSource
     */
    upstreamSourceId: number;
    /**
     * 
     * @type {string}
     * @memberof ArtistUpstreamSource
     */
    upstreamIdentifier: string | null;
}

export function ArtistUpstreamSourceFromJSON(json: any): ArtistUpstreamSource {
    return ArtistUpstreamSourceFromJSONTyped(json, false);
}

export function ArtistUpstreamSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArtistUpstreamSource {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'artistId': json['artist_id'],
        'upstreamSource': !exists(json, 'upstream_source') ? undefined : UpstreamSourceFromJSON(json['upstream_source']),
        'upstreamSourceId': json['upstream_source_id'],
        'upstreamIdentifier': json['upstream_identifier'],
    };
}

export function ArtistUpstreamSourceToJSON(value?: ArtistUpstreamSource | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'artist_id': value.artistId,
        'upstream_source': UpstreamSourceToJSON(value.upstreamSource),
        'upstream_source_id': value.upstreamSourceId,
        'upstream_identifier': value.upstreamIdentifier,
    };
}


