// tslint:disable
/**
 * Relisten API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ApiErrorCode,
    ApiErrorCodeFromJSON,
    ApiErrorCodeToJSON,
} from './';

/**
 * 
 * @export
 * @interface BooleanResponseEnvelope
 */
export interface BooleanResponseEnvelope  {
    /**
     * 
     * @type {boolean}
     * @memberof BooleanResponseEnvelope
     */
    success: boolean;
    /**
     * 
     * @type {ApiErrorCode}
     * @memberof BooleanResponseEnvelope
     */
    errorCode: ApiErrorCode;
    /**
     * 
     * @type {boolean}
     * @memberof BooleanResponseEnvelope
     */
    data: boolean;
}

export function BooleanResponseEnvelopeFromJSON(json: any): BooleanResponseEnvelope {
    return {
        'success': json['success'],
        'errorCode': ApiErrorCodeFromJSON(json['error_code']),
        'data': json['data'],
    };
}

export function BooleanResponseEnvelopeToJSON(value?: BooleanResponseEnvelope): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'success': value.success,
        'error_code': ApiErrorCodeToJSON(value.errorCode),
        'data': value.data,
    };
}


