/* tslint:disable */
/* eslint-disable */
/**
 * Relisten API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Era
 */
export interface Era {
    /**
     * 
     * @type {number}
     * @memberof Era
     */
    artistId: number;
    /**
     * 
     * @type {number}
     * @memberof Era
     */
    order: number;
    /**
     * 
     * @type {string}
     * @memberof Era
     */
    name: string | null;
    /**
     * 
     * @type {number}
     * @memberof Era
     */
    id: number;
    /**
     * 
     * @type {Date}
     * @memberof Era
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Era
     */
    updatedAt: Date;
}

export function EraFromJSON(json: any): Era {
    return EraFromJSONTyped(json, false);
}

export function EraFromJSONTyped(json: any, ignoreDiscriminator: boolean): Era {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'artistId': json['artist_id'],
        'order': json['order'],
        'name': json['name'],
        'id': json['id'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function EraToJSON(value?: Era | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'artist_id': value.artistId,
        'order': value.order,
        'name': value.name,
        'id': value.id,
        'created_at': (value.createdAt.toISOString()),
        'updated_at': (value.updatedAt.toISOString()),
    };
}


