// tslint:disable
/**
 * Relisten API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Link
 */
export interface Link  {
    /**
     * 
     * @type {number}
     * @memberof Link
     */
    sourceId: number;
    /**
     * 
     * @type {number}
     * @memberof Link
     */
    upstreamSourceId: number;
    /**
     * 
     * @type {boolean}
     * @memberof Link
     */
    forReviews: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Link
     */
    forRatings: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Link
     */
    forSource: boolean;
    /**
     * 
     * @type {string}
     * @memberof Link
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof Link
     */
    label: string;
    /**
     * 
     * @type {number}
     * @memberof Link
     */
    id: number;
    /**
     * 
     * @type {Date}
     * @memberof Link
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Link
     */
    updatedAt: Date;
}

export function LinkFromJSON(json: any): Link {
    return {
        'sourceId': json['source_id'],
        'upstreamSourceId': json['upstream_source_id'],
        'forReviews': json['for_reviews'],
        'forRatings': json['for_ratings'],
        'forSource': json['for_source'],
        'url': json['url'],
        'label': json['label'],
        'id': json['id'],
        'createdAt': new Date(json['created_at']),
        'updatedAt': new Date(json['updated_at']),
    };
}

export function LinkToJSON(value?: Link): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'source_id': value.sourceId,
        'upstream_source_id': value.upstreamSourceId,
        'for_reviews': value.forReviews,
        'for_ratings': value.forRatings,
        'for_source': value.forSource,
        'url': value.url,
        'label': value.label,
        'id': value.id,
        'created_at': value.createdAt.toISOString(),
        'updated_at': value.updatedAt.toISOString(),
    };
}


