/* tslint:disable */
/* eslint-disable */
/**
 * Relisten API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    SlimSourceWithShowVenueAndArtist,
    SlimSourceWithShowVenueAndArtistFromJSON,
    SlimSourceWithShowVenueAndArtistFromJSONTyped,
    SlimSourceWithShowVenueAndArtistToJSON,
    SourceTrack,
    SourceTrackFromJSON,
    SourceTrackFromJSONTyped,
    SourceTrackToJSON,
} from './';

/**
 * 
 * @export
 * @interface PlayedSourceTrack
 */
export interface PlayedSourceTrack {
    /**
     * 
     * @type {SlimSourceWithShowVenueAndArtist}
     * @memberof PlayedSourceTrack
     */
    source: SlimSourceWithShowVenueAndArtist;
    /**
     * 
     * @type {SourceTrack}
     * @memberof PlayedSourceTrack
     */
    track: SourceTrack;
}

export function PlayedSourceTrackFromJSON(json: any): PlayedSourceTrack {
    return PlayedSourceTrackFromJSONTyped(json, false);
}

export function PlayedSourceTrackFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlayedSourceTrack {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'source': SlimSourceWithShowVenueAndArtistFromJSON(json['source']),
        'track': SourceTrackFromJSON(json['track']),
    };
}

export function PlayedSourceTrackToJSON(value?: PlayedSourceTrack | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'source': SlimSourceWithShowVenueAndArtistToJSON(value.source),
        'track': SourceTrackToJSON(value.track),
    };
}


