/* tslint:disable */
/* eslint-disable */
/**
 * Relisten API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    SetlistSongWithSlimArtist,
    SetlistSongWithSlimArtistFromJSON,
    SetlistSongWithSlimArtistFromJSONTyped,
    SetlistSongWithSlimArtistToJSON,
    ShowWithSlimArtist,
    ShowWithSlimArtistFromJSON,
    ShowWithSlimArtistFromJSONTyped,
    ShowWithSlimArtistToJSON,
    SlimArtist,
    SlimArtistFromJSON,
    SlimArtistFromJSONTyped,
    SlimArtistToJSON,
    SourceWithSlimArtist,
    SourceWithSlimArtistFromJSON,
    SourceWithSlimArtistFromJSONTyped,
    SourceWithSlimArtistToJSON,
    TourWithSlimArtist,
    TourWithSlimArtistFromJSON,
    TourWithSlimArtistFromJSONTyped,
    TourWithSlimArtistToJSON,
    VenueWithSlimArtist,
    VenueWithSlimArtistFromJSON,
    VenueWithSlimArtistFromJSONTyped,
    VenueWithSlimArtistToJSON,
} from './';

/**
 * 
 * @export
 * @interface SearchResults
 */
export interface SearchResults {
    /**
     * 
     * @type {Array<SlimArtist>}
     * @memberof SearchResults
     */
    artists: Array<SlimArtist> | null;
    /**
     * 
     * @type {Array<ShowWithSlimArtist>}
     * @memberof SearchResults
     */
    shows: Array<ShowWithSlimArtist> | null;
    /**
     * 
     * @type {Array<SetlistSongWithSlimArtist>}
     * @memberof SearchResults
     */
    songs: Array<SetlistSongWithSlimArtist> | null;
    /**
     * 
     * @type {Array<SourceWithSlimArtist>}
     * @memberof SearchResults
     */
    source: Array<SourceWithSlimArtist> | null;
    /**
     * 
     * @type {Array<TourWithSlimArtist>}
     * @memberof SearchResults
     */
    tours: Array<TourWithSlimArtist> | null;
    /**
     * 
     * @type {Array<VenueWithSlimArtist>}
     * @memberof SearchResults
     */
    venues: Array<VenueWithSlimArtist> | null;
}

export function SearchResultsFromJSON(json: any): SearchResults {
    return SearchResultsFromJSONTyped(json, false);
}

export function SearchResultsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchResults {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'artists': (json['artists'] === null ? null : (json['artists'] as Array<any>).map(SlimArtistFromJSON)),
        'shows': (json['shows'] === null ? null : (json['shows'] as Array<any>).map(ShowWithSlimArtistFromJSON)),
        'songs': (json['songs'] === null ? null : (json['songs'] as Array<any>).map(SetlistSongWithSlimArtistFromJSON)),
        'source': (json['source'] === null ? null : (json['source'] as Array<any>).map(SourceWithSlimArtistFromJSON)),
        'tours': (json['tours'] === null ? null : (json['tours'] as Array<any>).map(TourWithSlimArtistFromJSON)),
        'venues': (json['venues'] === null ? null : (json['venues'] as Array<any>).map(VenueWithSlimArtistFromJSON)),
    };
}

export function SearchResultsToJSON(value?: SearchResults | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'artists': (value.artists === null ? null : (value.artists as Array<any>).map(SlimArtistToJSON)),
        'shows': (value.shows === null ? null : (value.shows as Array<any>).map(ShowWithSlimArtistToJSON)),
        'songs': (value.songs === null ? null : (value.songs as Array<any>).map(SetlistSongWithSlimArtistToJSON)),
        'source': (value.source === null ? null : (value.source as Array<any>).map(SourceWithSlimArtistToJSON)),
        'tours': (value.tours === null ? null : (value.tours as Array<any>).map(TourWithSlimArtistToJSON)),
        'venues': (value.venues === null ? null : (value.venues as Array<any>).map(VenueWithSlimArtistToJSON)),
    };
}


