// tslint:disable
/**
 * Relisten API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    SetlistSongWithSlimArtist,
    SetlistSongWithSlimArtistFromJSON,
    SetlistSongWithSlimArtistToJSON,
    ShowWithSlimArtist,
    ShowWithSlimArtistFromJSON,
    ShowWithSlimArtistToJSON,
    SlimArtist,
    SlimArtistFromJSON,
    SlimArtistToJSON,
    SourceWithSlimArtist,
    SourceWithSlimArtistFromJSON,
    SourceWithSlimArtistToJSON,
    TourWithSlimArtist,
    TourWithSlimArtistFromJSON,
    TourWithSlimArtistToJSON,
    VenueWithSlimArtist,
    VenueWithSlimArtistFromJSON,
    VenueWithSlimArtistToJSON,
} from './';

/**
 * 
 * @export
 * @interface SearchResults
 */
export interface SearchResults  {
    /**
     * 
     * @type {Array<SlimArtist>}
     * @memberof SearchResults
     */
    artists: Array<SlimArtist>;
    /**
     * 
     * @type {Array<ShowWithSlimArtist>}
     * @memberof SearchResults
     */
    shows: Array<ShowWithSlimArtist>;
    /**
     * 
     * @type {Array<SetlistSongWithSlimArtist>}
     * @memberof SearchResults
     */
    songs: Array<SetlistSongWithSlimArtist>;
    /**
     * 
     * @type {Array<SourceWithSlimArtist>}
     * @memberof SearchResults
     */
    source: Array<SourceWithSlimArtist>;
    /**
     * 
     * @type {Array<TourWithSlimArtist>}
     * @memberof SearchResults
     */
    tours: Array<TourWithSlimArtist>;
    /**
     * 
     * @type {Array<VenueWithSlimArtist>}
     * @memberof SearchResults
     */
    venues: Array<VenueWithSlimArtist>;
}

export function SearchResultsFromJSON(json: any): SearchResults {
    return {
        'artists': (json['artists'] as Array<any>).map(SlimArtistFromJSON),
        'shows': (json['shows'] as Array<any>).map(ShowWithSlimArtistFromJSON),
        'songs': (json['songs'] as Array<any>).map(SetlistSongWithSlimArtistFromJSON),
        'source': (json['source'] as Array<any>).map(SourceWithSlimArtistFromJSON),
        'tours': (json['tours'] as Array<any>).map(TourWithSlimArtistFromJSON),
        'venues': (json['venues'] as Array<any>).map(VenueWithSlimArtistFromJSON),
    };
}

export function SearchResultsToJSON(value?: SearchResults): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'artists': (value.artists as Array<any>).map(SlimArtistToJSON),
        'shows': (value.shows as Array<any>).map(ShowWithSlimArtistToJSON),
        'songs': (value.songs as Array<any>).map(SetlistSongWithSlimArtistToJSON),
        'source': (value.source as Array<any>).map(SourceWithSlimArtistToJSON),
        'tours': (value.tours as Array<any>).map(TourWithSlimArtistToJSON),
        'venues': (value.venues as Array<any>).map(VenueWithSlimArtistToJSON),
    };
}


