// tslint:disable
/**
 * Relisten API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetlistSongWithPlayCount
 */
export interface SetlistSongWithPlayCount  {
    /**
     * 
     * @type {number}
     * @memberof SetlistSongWithPlayCount
     */
    showsPlayedAt: number;
    /**
     * 
     * @type {number}
     * @memberof SetlistSongWithPlayCount
     */
    artistId: number;
    /**
     * 
     * @type {string}
     * @memberof SetlistSongWithPlayCount
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof SetlistSongWithPlayCount
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof SetlistSongWithPlayCount
     */
    upstreamIdentifier: string;
    /**
     * 
     * @type {string}
     * @memberof SetlistSongWithPlayCount
     */
    readonly sortName: string;
    /**
     * 
     * @type {string}
     * @memberof SetlistSongWithPlayCount
     */
    uuid: string;
    /**
     * 
     * @type {number}
     * @memberof SetlistSongWithPlayCount
     */
    id: number;
    /**
     * 
     * @type {Date}
     * @memberof SetlistSongWithPlayCount
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof SetlistSongWithPlayCount
     */
    updatedAt: Date;
}

export function SetlistSongWithPlayCountFromJSON(json: any): SetlistSongWithPlayCount {
    return {
        'showsPlayedAt': json['shows_played_at'],
        'artistId': json['artist_id'],
        'name': json['name'],
        'slug': json['slug'],
        'upstreamIdentifier': json['upstream_identifier'],
        'sortName': json['sortName'],
        'uuid': json['uuid'],
        'id': json['id'],
        'createdAt': new Date(json['created_at']),
        'updatedAt': new Date(json['updated_at']),
    };
}

export function SetlistSongWithPlayCountToJSON(value?: SetlistSongWithPlayCount): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'shows_played_at': value.showsPlayedAt,
        'artist_id': value.artistId,
        'name': value.name,
        'slug': value.slug,
        'upstream_identifier': value.upstreamIdentifier,
        'uuid': value.uuid,
        'id': value.id,
        'created_at': value.createdAt.toISOString(),
        'updated_at': value.updatedAt.toISOString(),
    };
}


