/* tslint:disable */
/* eslint-disable */
/**
 * Relisten API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    SlimArtist,
    SlimArtistFromJSON,
    SlimArtistFromJSONTyped,
    SlimArtistToJSON,
} from './';

/**
 * 
 * @export
 * @interface SetlistSongWithSlimArtist
 */
export interface SetlistSongWithSlimArtist {
    /**
     * 
     * @type {SlimArtist}
     * @memberof SetlistSongWithSlimArtist
     */
    slimArtist: SlimArtist;
    /**
     * 
     * @type {number}
     * @memberof SetlistSongWithSlimArtist
     */
    showsPlayedAt: number;
    /**
     * 
     * @type {number}
     * @memberof SetlistSongWithSlimArtist
     */
    artistId: number;
    /**
     * 
     * @type {string}
     * @memberof SetlistSongWithSlimArtist
     */
    name: string | null;
    /**
     * 
     * @type {string}
     * @memberof SetlistSongWithSlimArtist
     */
    slug: string | null;
    /**
     * 
     * @type {string}
     * @memberof SetlistSongWithSlimArtist
     */
    upstreamIdentifier: string | null;
    /**
     * 
     * @type {string}
     * @memberof SetlistSongWithSlimArtist
     */
    readonly sortName: string | null;
    /**
     * 
     * @type {string}
     * @memberof SetlistSongWithSlimArtist
     */
    uuid: string;
    /**
     * 
     * @type {number}
     * @memberof SetlistSongWithSlimArtist
     */
    id: number;
    /**
     * 
     * @type {Date}
     * @memberof SetlistSongWithSlimArtist
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof SetlistSongWithSlimArtist
     */
    updatedAt: Date;
}

export function SetlistSongWithSlimArtistFromJSON(json: any): SetlistSongWithSlimArtist {
    return SetlistSongWithSlimArtistFromJSONTyped(json, false);
}

export function SetlistSongWithSlimArtistFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetlistSongWithSlimArtist {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'slimArtist': SlimArtistFromJSON(json['slim_artist']),
        'showsPlayedAt': json['shows_played_at'],
        'artistId': json['artist_id'],
        'name': json['name'],
        'slug': json['slug'],
        'upstreamIdentifier': json['upstream_identifier'],
        'sortName': json['sortName'],
        'uuid': json['uuid'],
        'id': json['id'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function SetlistSongWithSlimArtistToJSON(value?: SetlistSongWithSlimArtist | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'slim_artist': SlimArtistToJSON(value.slimArtist),
        'shows_played_at': value.showsPlayedAt,
        'artist_id': value.artistId,
        'name': value.name,
        'slug': value.slug,
        'upstream_identifier': value.upstreamIdentifier,
        'uuid': value.uuid,
        'id': value.id,
        'created_at': (value.createdAt.toISOString()),
        'updated_at': (value.updatedAt.toISOString()),
    };
}


