// tslint:disable
/**
 * Relisten API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Era,
    EraFromJSON,
    EraToJSON,
    Tour,
    TourFromJSON,
    TourToJSON,
    VenueWithShowCount,
    VenueWithShowCountFromJSON,
    VenueWithShowCountToJSON,
    Year,
    YearFromJSON,
    YearToJSON,
} from './';

/**
 * 
 * @export
 * @interface Show
 */
export interface Show  {
    /**
     * 
     * @type {number}
     * @memberof Show
     */
    artistId: number;
    /**
     * 
     * @type {number}
     * @memberof Show
     */
    venueId?: number;
    /**
     * 
     * @type {VenueWithShowCount}
     * @memberof Show
     */
    venue?: VenueWithShowCount;
    /**
     * 
     * @type {number}
     * @memberof Show
     */
    tourId?: number;
    /**
     * 
     * @type {Tour}
     * @memberof Show
     */
    tour?: Tour;
    /**
     * 
     * @type {number}
     * @memberof Show
     */
    yearId?: number;
    /**
     * 
     * @type {Year}
     * @memberof Show
     */
    year?: Year;
    /**
     * 
     * @type {number}
     * @memberof Show
     */
    eraId?: number;
    /**
     * 
     * @type {Era}
     * @memberof Show
     */
    era?: Era;
    /**
     * 
     * @type {Date}
     * @memberof Show
     */
    date: Date;
    /**
     * 
     * @type {number}
     * @memberof Show
     */
    avgRating: number;
    /**
     * 
     * @type {number}
     * @memberof Show
     */
    avgDuration?: number;
    /**
     * 
     * @type {string}
     * @memberof Show
     */
    displayDate: string;
    /**
     * 
     * @type {Date}
     * @memberof Show
     */
    mostRecentSourceUpdatedAt: Date;
    /**
     * 
     * @type {boolean}
     * @memberof Show
     */
    hasSoundboardSource: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Show
     */
    hasStreamableFlacSource: boolean;
    /**
     * 
     * @type {number}
     * @memberof Show
     */
    sourceCount: number;
    /**
     * 
     * @type {string}
     * @memberof Show
     */
    uuid: string;
    /**
     * 
     * @type {number}
     * @memberof Show
     */
    id: number;
    /**
     * 
     * @type {Date}
     * @memberof Show
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Show
     */
    updatedAt: Date;
}

export function ShowFromJSON(json: any): Show {
    return {
        'artistId': json['artist_id'],
        'venueId': !exists(json, 'venue_id') ? undefined : json['venue_id'],
        'venue': !exists(json, 'venue') ? undefined : VenueWithShowCountFromJSON(json['venue']),
        'tourId': !exists(json, 'tour_id') ? undefined : json['tour_id'],
        'tour': !exists(json, 'tour') ? undefined : TourFromJSON(json['tour']),
        'yearId': !exists(json, 'year_id') ? undefined : json['year_id'],
        'year': !exists(json, 'year') ? undefined : YearFromJSON(json['year']),
        'eraId': !exists(json, 'era_id') ? undefined : json['era_id'],
        'era': !exists(json, 'era') ? undefined : EraFromJSON(json['era']),
        'date': new Date(json['date']),
        'avgRating': json['avg_rating'],
        'avgDuration': !exists(json, 'avg_duration') ? undefined : json['avg_duration'],
        'displayDate': json['display_date'],
        'mostRecentSourceUpdatedAt': new Date(json['most_recent_source_updated_at']),
        'hasSoundboardSource': json['has_soundboard_source'],
        'hasStreamableFlacSource': json['has_streamable_flac_source'],
        'sourceCount': json['source_count'],
        'uuid': json['uuid'],
        'id': json['id'],
        'createdAt': new Date(json['created_at']),
        'updatedAt': new Date(json['updated_at']),
    };
}

export function ShowToJSON(value?: Show): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'artist_id': value.artistId,
        'venue_id': value.venueId,
        'venue': VenueWithShowCountToJSON(value.venue),
        'tour_id': value.tourId,
        'tour': TourToJSON(value.tour),
        'year_id': value.yearId,
        'year': YearToJSON(value.year),
        'era_id': value.eraId,
        'era': EraToJSON(value.era),
        'date': value.date.toISOString(),
        'avg_rating': value.avgRating,
        'avg_duration': value.avgDuration,
        'display_date': value.displayDate,
        'most_recent_source_updated_at': value.mostRecentSourceUpdatedAt.toISOString(),
        'has_soundboard_source': value.hasSoundboardSource,
        'has_streamable_flac_source': value.hasStreamableFlacSource,
        'source_count': value.sourceCount,
        'uuid': value.uuid,
        'id': value.id,
        'created_at': value.createdAt.toISOString(),
        'updated_at': value.updatedAt.toISOString(),
    };
}


