/* tslint:disable */
/* eslint-disable */
/**
 * Relisten API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Era,
    EraFromJSON,
    EraFromJSONTyped,
    EraToJSON,
    SourceFull,
    SourceFullFromJSON,
    SourceFullFromJSONTyped,
    SourceFullToJSON,
    Tour,
    TourFromJSON,
    TourFromJSONTyped,
    TourToJSON,
    VenueWithShowCount,
    VenueWithShowCountFromJSON,
    VenueWithShowCountFromJSONTyped,
    VenueWithShowCountToJSON,
    Year,
    YearFromJSON,
    YearFromJSONTyped,
    YearToJSON,
} from './';

/**
 * 
 * @export
 * @interface ShowWithSources
 */
export interface ShowWithSources {
    /**
     * 
     * @type {Array<SourceFull>}
     * @memberof ShowWithSources
     */
    sources: Array<SourceFull> | null;
    /**
     * 
     * @type {number}
     * @memberof ShowWithSources
     */
    artistId: number;
    /**
     * 
     * @type {number}
     * @memberof ShowWithSources
     */
    venueId?: number | null;
    /**
     * 
     * @type {VenueWithShowCount}
     * @memberof ShowWithSources
     */
    venue?: VenueWithShowCount;
    /**
     * 
     * @type {number}
     * @memberof ShowWithSources
     */
    tourId?: number | null;
    /**
     * 
     * @type {Tour}
     * @memberof ShowWithSources
     */
    tour?: Tour;
    /**
     * 
     * @type {number}
     * @memberof ShowWithSources
     */
    yearId?: number | null;
    /**
     * 
     * @type {Year}
     * @memberof ShowWithSources
     */
    year?: Year;
    /**
     * 
     * @type {number}
     * @memberof ShowWithSources
     */
    eraId?: number | null;
    /**
     * 
     * @type {Era}
     * @memberof ShowWithSources
     */
    era?: Era;
    /**
     * 
     * @type {Date}
     * @memberof ShowWithSources
     */
    date: Date;
    /**
     * 
     * @type {number}
     * @memberof ShowWithSources
     */
    avgRating: number;
    /**
     * 
     * @type {number}
     * @memberof ShowWithSources
     */
    avgDuration?: number | null;
    /**
     * 
     * @type {string}
     * @memberof ShowWithSources
     */
    displayDate: string | null;
    /**
     * 
     * @type {Date}
     * @memberof ShowWithSources
     */
    mostRecentSourceUpdatedAt: Date;
    /**
     * 
     * @type {boolean}
     * @memberof ShowWithSources
     */
    hasSoundboardSource: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ShowWithSources
     */
    hasStreamableFlacSource: boolean;
    /**
     * 
     * @type {number}
     * @memberof ShowWithSources
     */
    sourceCount: number;
    /**
     * 
     * @type {string}
     * @memberof ShowWithSources
     */
    uuid: string;
    /**
     * 
     * @type {number}
     * @memberof ShowWithSources
     */
    id: number;
    /**
     * 
     * @type {Date}
     * @memberof ShowWithSources
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof ShowWithSources
     */
    updatedAt: Date;
}

export function ShowWithSourcesFromJSON(json: any): ShowWithSources {
    return ShowWithSourcesFromJSONTyped(json, false);
}

export function ShowWithSourcesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShowWithSources {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'sources': (json['sources'] === null ? null : (json['sources'] as Array<any>).map(SourceFullFromJSON)),
        'artistId': json['artist_id'],
        'venueId': !exists(json, 'venue_id') ? undefined : json['venue_id'],
        'venue': !exists(json, 'venue') ? undefined : VenueWithShowCountFromJSON(json['venue']),
        'tourId': !exists(json, 'tour_id') ? undefined : json['tour_id'],
        'tour': !exists(json, 'tour') ? undefined : TourFromJSON(json['tour']),
        'yearId': !exists(json, 'year_id') ? undefined : json['year_id'],
        'year': !exists(json, 'year') ? undefined : YearFromJSON(json['year']),
        'eraId': !exists(json, 'era_id') ? undefined : json['era_id'],
        'era': !exists(json, 'era') ? undefined : EraFromJSON(json['era']),
        'date': (new Date(json['date'])),
        'avgRating': json['avg_rating'],
        'avgDuration': !exists(json, 'avg_duration') ? undefined : json['avg_duration'],
        'displayDate': json['display_date'],
        'mostRecentSourceUpdatedAt': (new Date(json['most_recent_source_updated_at'])),
        'hasSoundboardSource': json['has_soundboard_source'],
        'hasStreamableFlacSource': json['has_streamable_flac_source'],
        'sourceCount': json['source_count'],
        'uuid': json['uuid'],
        'id': json['id'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function ShowWithSourcesToJSON(value?: ShowWithSources | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'sources': (value.sources === null ? null : (value.sources as Array<any>).map(SourceFullToJSON)),
        'artist_id': value.artistId,
        'venue_id': value.venueId,
        'venue': VenueWithShowCountToJSON(value.venue),
        'tour_id': value.tourId,
        'tour': TourToJSON(value.tour),
        'year_id': value.yearId,
        'year': YearToJSON(value.year),
        'era_id': value.eraId,
        'era': EraToJSON(value.era),
        'date': (value.date.toISOString()),
        'avg_rating': value.avgRating,
        'avg_duration': value.avgDuration,
        'display_date': value.displayDate,
        'most_recent_source_updated_at': (value.mostRecentSourceUpdatedAt.toISOString()),
        'has_soundboard_source': value.hasSoundboardSource,
        'has_streamable_flac_source': value.hasStreamableFlacSource,
        'source_count': value.sourceCount,
        'uuid': value.uuid,
        'id': value.id,
        'created_at': (value.createdAt.toISOString()),
        'updated_at': (value.updatedAt.toISOString()),
    };
}


