// tslint:disable
/**
 * Relisten API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SlimArtist
 */
export interface SlimArtist  {
    /**
     * 
     * @type {string}
     * @memberof SlimArtist
     */
    musicbrainzId: string;
    /**
     * 
     * @type {string}
     * @memberof SlimArtist
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof SlimArtist
     */
    featured: number;
    /**
     * 
     * @type {string}
     * @memberof SlimArtist
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof SlimArtist
     */
    sortName: string;
    /**
     * 
     * @type {string}
     * @memberof SlimArtist
     */
    uuid: string;
    /**
     * 
     * @type {number}
     * @memberof SlimArtist
     */
    id: number;
    /**
     * 
     * @type {Date}
     * @memberof SlimArtist
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof SlimArtist
     */
    updatedAt: Date;
}

export function SlimArtistFromJSON(json: any): SlimArtist {
    return {
        'musicbrainzId': json['musicbrainz_id'],
        'name': json['name'],
        'featured': json['featured'],
        'slug': json['slug'],
        'sortName': json['sort_name'],
        'uuid': json['uuid'],
        'id': json['id'],
        'createdAt': new Date(json['created_at']),
        'updatedAt': new Date(json['updated_at']),
    };
}

export function SlimArtistToJSON(value?: SlimArtist): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'musicbrainz_id': value.musicbrainzId,
        'name': value.name,
        'featured': value.featured,
        'slug': value.slug,
        'sort_name': value.sortName,
        'uuid': value.uuid,
        'id': value.id,
        'created_at': value.createdAt.toISOString(),
        'updated_at': value.updatedAt.toISOString(),
    };
}


