// tslint:disable
/**
 * Relisten API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Show,
    ShowFromJSON,
    ShowToJSON,
    SlimArtistWithFeatures,
    SlimArtistWithFeaturesFromJSON,
    SlimArtistWithFeaturesToJSON,
    Venue,
    VenueFromJSON,
    VenueToJSON,
} from './';

/**
 * 
 * @export
 * @interface SlimSourceWithShowVenueAndArtist
 */
export interface SlimSourceWithShowVenueAndArtist  {
    /**
     * 
     * @type {number}
     * @memberof SlimSourceWithShowVenueAndArtist
     */
    showId?: number;
    /**
     * 
     * @type {Show}
     * @memberof SlimSourceWithShowVenueAndArtist
     */
    show: Show;
    /**
     * 
     * @type {SlimArtistWithFeatures}
     * @memberof SlimSourceWithShowVenueAndArtist
     */
    artist: SlimArtistWithFeatures;
    /**
     * 
     * @type {number}
     * @memberof SlimSourceWithShowVenueAndArtist
     */
    artistId: number;
    /**
     * 
     * @type {number}
     * @memberof SlimSourceWithShowVenueAndArtist
     */
    venueId?: number;
    /**
     * 
     * @type {Venue}
     * @memberof SlimSourceWithShowVenueAndArtist
     */
    venue?: Venue;
    /**
     * 
     * @type {string}
     * @memberof SlimSourceWithShowVenueAndArtist
     */
    displayDate: string;
    /**
     * 
     * @type {boolean}
     * @memberof SlimSourceWithShowVenueAndArtist
     */
    isSoundboard: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SlimSourceWithShowVenueAndArtist
     */
    isRemaster: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SlimSourceWithShowVenueAndArtist
     */
    hasJamcharts: boolean;
    /**
     * 
     * @type {number}
     * @memberof SlimSourceWithShowVenueAndArtist
     */
    avgRating: number;
    /**
     * 
     * @type {number}
     * @memberof SlimSourceWithShowVenueAndArtist
     */
    numReviews: number;
    /**
     * 
     * @type {number}
     * @memberof SlimSourceWithShowVenueAndArtist
     */
    numRatings?: number;
    /**
     * 
     * @type {number}
     * @memberof SlimSourceWithShowVenueAndArtist
     */
    avgRatingWeighted: number;
    /**
     * 
     * @type {number}
     * @memberof SlimSourceWithShowVenueAndArtist
     */
    duration?: number;
    /**
     * 
     * @type {string}
     * @memberof SlimSourceWithShowVenueAndArtist
     */
    upstreamIdentifier: string;
    /**
     * 
     * @type {string}
     * @memberof SlimSourceWithShowVenueAndArtist
     */
    uuid: string;
    /**
     * 
     * @type {number}
     * @memberof SlimSourceWithShowVenueAndArtist
     */
    id: number;
    /**
     * 
     * @type {Date}
     * @memberof SlimSourceWithShowVenueAndArtist
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof SlimSourceWithShowVenueAndArtist
     */
    updatedAt: Date;
}

export function SlimSourceWithShowVenueAndArtistFromJSON(json: any): SlimSourceWithShowVenueAndArtist {
    return {
        'showId': !exists(json, 'show_id') ? undefined : json['show_id'],
        'show': ShowFromJSON(json['show']),
        'artist': SlimArtistWithFeaturesFromJSON(json['artist']),
        'artistId': json['artist_id'],
        'venueId': !exists(json, 'venue_id') ? undefined : json['venue_id'],
        'venue': !exists(json, 'venue') ? undefined : VenueFromJSON(json['venue']),
        'displayDate': json['display_date'],
        'isSoundboard': json['is_soundboard'],
        'isRemaster': json['is_remaster'],
        'hasJamcharts': json['has_jamcharts'],
        'avgRating': json['avg_rating'],
        'numReviews': json['num_reviews'],
        'numRatings': !exists(json, 'num_ratings') ? undefined : json['num_ratings'],
        'avgRatingWeighted': json['avg_rating_weighted'],
        'duration': !exists(json, 'duration') ? undefined : json['duration'],
        'upstreamIdentifier': json['upstream_identifier'],
        'uuid': json['uuid'],
        'id': json['id'],
        'createdAt': new Date(json['created_at']),
        'updatedAt': new Date(json['updated_at']),
    };
}

export function SlimSourceWithShowVenueAndArtistToJSON(value?: SlimSourceWithShowVenueAndArtist): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'show_id': value.showId,
        'show': ShowToJSON(value.show),
        'artist': SlimArtistWithFeaturesToJSON(value.artist),
        'artist_id': value.artistId,
        'venue_id': value.venueId,
        'venue': VenueToJSON(value.venue),
        'display_date': value.displayDate,
        'is_soundboard': value.isSoundboard,
        'is_remaster': value.isRemaster,
        'has_jamcharts': value.hasJamcharts,
        'avg_rating': value.avgRating,
        'num_reviews': value.numReviews,
        'num_ratings': value.numRatings,
        'avg_rating_weighted': value.avgRatingWeighted,
        'duration': value.duration,
        'upstream_identifier': value.upstreamIdentifier,
        'uuid': value.uuid,
        'id': value.id,
        'created_at': value.createdAt.toISOString(),
        'updated_at': value.updatedAt.toISOString(),
    };
}


