/* tslint:disable */
/* eslint-disable */
/**
 * Relisten API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ApiErrorCode,
    ApiErrorCodeFromJSON,
    ApiErrorCodeFromJSONTyped,
    ApiErrorCodeToJSON,
    SourceTrackPlay,
    SourceTrackPlayFromJSON,
    SourceTrackPlayFromJSONTyped,
    SourceTrackPlayToJSON,
} from './';

/**
 * 
 * @export
 * @interface SourceTrackPlayResponseEnvelope
 */
export interface SourceTrackPlayResponseEnvelope {
    /**
     * 
     * @type {boolean}
     * @memberof SourceTrackPlayResponseEnvelope
     */
    success: boolean;
    /**
     * 
     * @type {ApiErrorCode}
     * @memberof SourceTrackPlayResponseEnvelope
     */
    errorCode: ApiErrorCode;
    /**
     * 
     * @type {SourceTrackPlay}
     * @memberof SourceTrackPlayResponseEnvelope
     */
    data: SourceTrackPlay;
}

export function SourceTrackPlayResponseEnvelopeFromJSON(json: any): SourceTrackPlayResponseEnvelope {
    return SourceTrackPlayResponseEnvelopeFromJSONTyped(json, false);
}

export function SourceTrackPlayResponseEnvelopeFromJSONTyped(json: any, ignoreDiscriminator: boolean): SourceTrackPlayResponseEnvelope {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': json['success'],
        'errorCode': ApiErrorCodeFromJSON(json['error_code']),
        'data': SourceTrackPlayFromJSON(json['data']),
    };
}

export function SourceTrackPlayResponseEnvelopeToJSON(value?: SourceTrackPlayResponseEnvelope | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'error_code': ApiErrorCodeToJSON(value.errorCode),
        'data': SourceTrackPlayToJSON(value.data),
    };
}


