/* tslint:disable */
/* eslint-disable */
/**
 * Relisten API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SourceReview
 */
export interface SourceReview {
    /**
     * 
     * @type {number}
     * @memberof SourceReview
     */
    sourceId: number;
    /**
     * 
     * @type {number}
     * @memberof SourceReview
     */
    rating?: number | null;
    /**
     * 
     * @type {string}
     * @memberof SourceReview
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SourceReview
     */
    review: string | null;
    /**
     * 
     * @type {string}
     * @memberof SourceReview
     */
    author?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SourceReview
     */
    uuid: string;
    /**
     * 
     * @type {number}
     * @memberof SourceReview
     */
    id: number;
    /**
     * 
     * @type {Date}
     * @memberof SourceReview
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof SourceReview
     */
    updatedAt: Date;
}

export function SourceReviewFromJSON(json: any): SourceReview {
    return SourceReviewFromJSONTyped(json, false);
}

export function SourceReviewFromJSONTyped(json: any, ignoreDiscriminator: boolean): SourceReview {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'sourceId': json['source_id'],
        'rating': !exists(json, 'rating') ? undefined : json['rating'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'review': json['review'],
        'author': !exists(json, 'author') ? undefined : json['author'],
        'uuid': json['uuid'],
        'id': json['id'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function SourceReviewToJSON(value?: SourceReview | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'source_id': value.sourceId,
        'rating': value.rating,
        'title': value.title,
        'review': value.review,
        'author': value.author,
        'uuid': value.uuid,
        'id': value.id,
        'created_at': (value.createdAt.toISOString()),
        'updated_at': (value.updatedAt.toISOString()),
    };
}


