/* tslint:disable */
/* eslint-disable */
/**
 * Relisten API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Show,
    ShowFromJSON,
    ShowFromJSONTyped,
    ShowToJSON,
} from './';

/**
 * 
 * @export
 * @interface TourWithShows
 */
export interface TourWithShows {
    /**
     * 
     * @type {Array<Show>}
     * @memberof TourWithShows
     */
    shows: Array<Show> | null;
    /**
     * 
     * @type {number}
     * @memberof TourWithShows
     */
    artistId: number;
    /**
     * 
     * @type {Date}
     * @memberof TourWithShows
     */
    startDate: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof TourWithShows
     */
    endDate: Date | null;
    /**
     * 
     * @type {string}
     * @memberof TourWithShows
     */
    name: string | null;
    /**
     * 
     * @type {string}
     * @memberof TourWithShows
     */
    slug: string | null;
    /**
     * 
     * @type {string}
     * @memberof TourWithShows
     */
    upstreamIdentifier: string | null;
    /**
     * 
     * @type {string}
     * @memberof TourWithShows
     */
    uuid: string;
    /**
     * 
     * @type {number}
     * @memberof TourWithShows
     */
    id: number;
    /**
     * 
     * @type {Date}
     * @memberof TourWithShows
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof TourWithShows
     */
    updatedAt: Date;
}

export function TourWithShowsFromJSON(json: any): TourWithShows {
    return TourWithShowsFromJSONTyped(json, false);
}

export function TourWithShowsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TourWithShows {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'shows': (json['shows'] === null ? null : (json['shows'] as Array<any>).map(ShowFromJSON)),
        'artistId': json['artist_id'],
        'startDate': (json['start_date'] === null ? null : new Date(json['start_date'])),
        'endDate': (json['end_date'] === null ? null : new Date(json['end_date'])),
        'name': json['name'],
        'slug': json['slug'],
        'upstreamIdentifier': json['upstream_identifier'],
        'uuid': json['uuid'],
        'id': json['id'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function TourWithShowsToJSON(value?: TourWithShows | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'shows': (value.shows === null ? null : (value.shows as Array<any>).map(ShowToJSON)),
        'artist_id': value.artistId,
        'start_date': (value.startDate === null ? null : value.startDate.toISOString()),
        'end_date': (value.endDate === null ? null : value.endDate.toISOString()),
        'name': value.name,
        'slug': value.slug,
        'upstream_identifier': value.upstreamIdentifier,
        'uuid': value.uuid,
        'id': value.id,
        'created_at': (value.createdAt.toISOString()),
        'updated_at': (value.updatedAt.toISOString()),
    };
}


