/* tslint:disable */
/* eslint-disable */
/**
 * Relisten API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpstreamSource
 */
export interface UpstreamSource {
    /**
     * 
     * @type {number}
     * @memberof UpstreamSource
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof UpstreamSource
     */
    name: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpstreamSource
     */
    url: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpstreamSource
     */
    description: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpstreamSource
     */
    creditLine: string | null;
}

export function UpstreamSourceFromJSON(json: any): UpstreamSource {
    return UpstreamSourceFromJSONTyped(json, false);
}

export function UpstreamSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpstreamSource {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'url': json['url'],
        'description': json['description'],
        'creditLine': json['credit_line'],
    };
}

export function UpstreamSourceToJSON(value?: UpstreamSource | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'url': value.url,
        'description': value.description,
        'credit_line': value.creditLine,
    };
}


