// tslint:disable
/**
 * Relisten API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpstreamSource
 */
export interface UpstreamSource  {
    /**
     * 
     * @type {number}
     * @memberof UpstreamSource
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof UpstreamSource
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UpstreamSource
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof UpstreamSource
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof UpstreamSource
     */
    creditLine: string;
}

export function UpstreamSourceFromJSON(json: any): UpstreamSource {
    return {
        'id': json['id'],
        'name': json['name'],
        'url': json['url'],
        'description': json['description'],
        'creditLine': json['credit_line'],
    };
}

export function UpstreamSourceToJSON(value?: UpstreamSource): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'id': value.id,
        'name': value.name,
        'url': value.url,
        'description': value.description,
        'credit_line': value.creditLine,
    };
}


