/* tslint:disable */
/* eslint-disable */
/**
 * Relisten API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Show,
    ShowFromJSON,
    ShowFromJSONTyped,
    ShowToJSON,
} from './';

/**
 * 
 * @export
 * @interface VenueWithShows
 */
export interface VenueWithShows {
    /**
     * 
     * @type {Array<Show>}
     * @memberof VenueWithShows
     */
    shows: Array<Show> | null;
    /**
     * 
     * @type {number}
     * @memberof VenueWithShows
     */
    showsAtVenue: number;
    /**
     * 
     * @type {number}
     * @memberof VenueWithShows
     */
    artistId: number;
    /**
     * 
     * @type {number}
     * @memberof VenueWithShows
     */
    latitude?: number | null;
    /**
     * 
     * @type {number}
     * @memberof VenueWithShows
     */
    longitude?: number | null;
    /**
     * 
     * @type {string}
     * @memberof VenueWithShows
     */
    name: string | null;
    /**
     * 
     * @type {string}
     * @memberof VenueWithShows
     */
    location: string | null;
    /**
     * 
     * @type {string}
     * @memberof VenueWithShows
     */
    upstreamIdentifier: string | null;
    /**
     * 
     * @type {string}
     * @memberof VenueWithShows
     */
    slug: string | null;
    /**
     * 
     * @type {string}
     * @memberof VenueWithShows
     */
    pastNames?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VenueWithShows
     */
    readonly sortName: string | null;
    /**
     * 
     * @type {string}
     * @memberof VenueWithShows
     */
    uuid: string;
    /**
     * 
     * @type {number}
     * @memberof VenueWithShows
     */
    id: number;
    /**
     * 
     * @type {Date}
     * @memberof VenueWithShows
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof VenueWithShows
     */
    updatedAt: Date;
}

export function VenueWithShowsFromJSON(json: any): VenueWithShows {
    return VenueWithShowsFromJSONTyped(json, false);
}

export function VenueWithShowsFromJSONTyped(json: any, ignoreDiscriminator: boolean): VenueWithShows {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'shows': (json['shows'] === null ? null : (json['shows'] as Array<any>).map(ShowFromJSON)),
        'showsAtVenue': json['shows_at_venue'],
        'artistId': json['artist_id'],
        'latitude': !exists(json, 'latitude') ? undefined : json['latitude'],
        'longitude': !exists(json, 'longitude') ? undefined : json['longitude'],
        'name': json['name'],
        'location': json['location'],
        'upstreamIdentifier': json['upstream_identifier'],
        'slug': json['slug'],
        'pastNames': !exists(json, 'past_names') ? undefined : json['past_names'],
        'sortName': json['sortName'],
        'uuid': json['uuid'],
        'id': json['id'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function VenueWithShowsToJSON(value?: VenueWithShows | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'shows': (value.shows === null ? null : (value.shows as Array<any>).map(ShowToJSON)),
        'shows_at_venue': value.showsAtVenue,
        'artist_id': value.artistId,
        'latitude': value.latitude,
        'longitude': value.longitude,
        'name': value.name,
        'location': value.location,
        'upstream_identifier': value.upstreamIdentifier,
        'slug': value.slug,
        'past_names': value.pastNames,
        'uuid': value.uuid,
        'id': value.id,
        'created_at': (value.createdAt.toISOString()),
        'updated_at': (value.updatedAt.toISOString()),
    };
}


