/* tslint:disable */
/* eslint-disable */
/**
 * Relisten API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Year
 */
export interface Year {
    /**
     * 
     * @type {number}
     * @memberof Year
     */
    showCount: number;
    /**
     * 
     * @type {number}
     * @memberof Year
     */
    sourceCount: number;
    /**
     * 
     * @type {number}
     * @memberof Year
     */
    duration?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Year
     */
    avgDuration?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Year
     */
    avgRating: number;
    /**
     * 
     * @type {string}
     * @memberof Year
     */
    year: string | null;
    /**
     * 
     * @type {number}
     * @memberof Year
     */
    artistId: number;
    /**
     * 
     * @type {string}
     * @memberof Year
     */
    uuid: string;
    /**
     * 
     * @type {number}
     * @memberof Year
     */
    id: number;
    /**
     * 
     * @type {Date}
     * @memberof Year
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Year
     */
    updatedAt: Date;
}

export function YearFromJSON(json: any): Year {
    return YearFromJSONTyped(json, false);
}

export function YearFromJSONTyped(json: any, ignoreDiscriminator: boolean): Year {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'showCount': json['show_count'],
        'sourceCount': json['source_count'],
        'duration': !exists(json, 'duration') ? undefined : json['duration'],
        'avgDuration': !exists(json, 'avg_duration') ? undefined : json['avg_duration'],
        'avgRating': json['avg_rating'],
        'year': json['year'],
        'artistId': json['artist_id'],
        'uuid': json['uuid'],
        'id': json['id'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function YearToJSON(value?: Year | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'show_count': value.showCount,
        'source_count': value.sourceCount,
        'duration': value.duration,
        'avg_duration': value.avgDuration,
        'avg_rating': value.avgRating,
        'year': value.year,
        'artist_id': value.artistId,
        'uuid': value.uuid,
        'id': value.id,
        'created_at': (value.createdAt.toISOString()),
        'updated_at': (value.updatedAt.toISOString()),
    };
}


