/* tslint:disable */
/* eslint-disable */
/**
 * Relisten API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    BooleanResponseEnvelope,
    BooleanResponseEnvelopeFromJSON,
    BooleanResponseEnvelopeToJSON,
    Era,
    EraFromJSON,
    EraToJSON,
} from '../models';

export interface ApiV2ArtistsArtistIdOrSlugErasGetRequest {
    artistIdOrSlug: string;
}

/**
 * 
 */
export class ErasApi extends runtime.BaseAPI {

    /**
     */
    async apiV2ArtistsArtistIdOrSlugErasGetRaw(requestParameters: ApiV2ArtistsArtistIdOrSlugErasGetRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<Era>>> {
        if (requestParameters.artistIdOrSlug === null || requestParameters.artistIdOrSlug === undefined) {
            throw new runtime.RequiredError('artistIdOrSlug','Required parameter requestParameters.artistIdOrSlug was null or undefined when calling apiV2ArtistsArtistIdOrSlugErasGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v2/artists/{artistIdOrSlug}/eras`.replace(`{${"artistIdOrSlug"}}`, encodeURIComponent(String(requestParameters.artistIdOrSlug))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(EraFromJSON));
    }

    /**
     */
    async apiV2ArtistsArtistIdOrSlugErasGet(requestParameters: ApiV2ArtistsArtistIdOrSlugErasGetRequest, initOverrides?: RequestInit): Promise<Array<Era>> {
        const response = await this.apiV2ArtistsArtistIdOrSlugErasGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
