/* tslint:disable */
/* eslint-disable */
/**
 * Relisten API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    SearchResults,
    SearchResultsFromJSON,
    SearchResultsToJSON,
} from '../models';

export interface ApiV2SearchGetRequest {
    q?: string;
    artistId?: number;
}

/**
 * 
 */
export class SearchApi extends runtime.BaseAPI {

    /**
     */
    async apiV2SearchGetRaw(requestParameters: ApiV2SearchGetRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<SearchResults>> {
        const queryParameters: any = {};

        if (requestParameters.q !== undefined) {
            queryParameters['q'] = requestParameters.q;
        }

        if (requestParameters.artistId !== undefined) {
            queryParameters['artist_id'] = requestParameters.artistId;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v2/search`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SearchResultsFromJSON(jsonValue));
    }

    /**
     */
    async apiV2SearchGet(requestParameters: ApiV2SearchGetRequest, initOverrides?: RequestInit): Promise<SearchResults> {
        const response = await this.apiV2SearchGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
