/* tslint:disable */
/* eslint-disable */
/**
 * Relisten API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    BooleanResponseEnvelope,
    BooleanResponseEnvelopeFromJSON,
    BooleanResponseEnvelopeToJSON,
    SetlistSongWithPlayCount,
    SetlistSongWithPlayCountFromJSON,
    SetlistSongWithPlayCountToJSON,
    SetlistSongWithShows,
    SetlistSongWithShowsFromJSON,
    SetlistSongWithShowsToJSON,
} from '../models';

export interface ApiV2ArtistsArtistIdOrSlugSongsGetRequest {
    artistIdOrSlug: string;
}

export interface ApiV2ArtistsArtistIdOrSlugSongsIdAndSlugGetRequest {
    artistIdOrSlug: string;
    idAndSlug: string;
}

/**
 * 
 */
export class SongsApi extends runtime.BaseAPI {

    /**
     */
    async apiV2ArtistsArtistIdOrSlugSongsGetRaw(requestParameters: ApiV2ArtistsArtistIdOrSlugSongsGetRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<SetlistSongWithPlayCount>>> {
        if (requestParameters.artistIdOrSlug === null || requestParameters.artistIdOrSlug === undefined) {
            throw new runtime.RequiredError('artistIdOrSlug','Required parameter requestParameters.artistIdOrSlug was null or undefined when calling apiV2ArtistsArtistIdOrSlugSongsGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v2/artists/{artistIdOrSlug}/songs`.replace(`{${"artistIdOrSlug"}}`, encodeURIComponent(String(requestParameters.artistIdOrSlug))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SetlistSongWithPlayCountFromJSON));
    }

    /**
     */
    async apiV2ArtistsArtistIdOrSlugSongsGet(requestParameters: ApiV2ArtistsArtistIdOrSlugSongsGetRequest, initOverrides?: RequestInit): Promise<Array<SetlistSongWithPlayCount>> {
        const response = await this.apiV2ArtistsArtistIdOrSlugSongsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiV2ArtistsArtistIdOrSlugSongsIdAndSlugGetRaw(requestParameters: ApiV2ArtistsArtistIdOrSlugSongsIdAndSlugGetRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<SetlistSongWithShows>> {
        if (requestParameters.artistIdOrSlug === null || requestParameters.artistIdOrSlug === undefined) {
            throw new runtime.RequiredError('artistIdOrSlug','Required parameter requestParameters.artistIdOrSlug was null or undefined when calling apiV2ArtistsArtistIdOrSlugSongsIdAndSlugGet.');
        }

        if (requestParameters.idAndSlug === null || requestParameters.idAndSlug === undefined) {
            throw new runtime.RequiredError('idAndSlug','Required parameter requestParameters.idAndSlug was null or undefined when calling apiV2ArtistsArtistIdOrSlugSongsIdAndSlugGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v2/artists/{artistIdOrSlug}/songs/{idAndSlug}`.replace(`{${"artistIdOrSlug"}}`, encodeURIComponent(String(requestParameters.artistIdOrSlug))).replace(`{${"idAndSlug"}}`, encodeURIComponent(String(requestParameters.idAndSlug))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SetlistSongWithShowsFromJSON(jsonValue));
    }

    /**
     */
    async apiV2ArtistsArtistIdOrSlugSongsIdAndSlugGet(requestParameters: ApiV2ArtistsArtistIdOrSlugSongsIdAndSlugGetRequest, initOverrides?: RequestInit): Promise<SetlistSongWithShows> {
        const response = await this.apiV2ArtistsArtistIdOrSlugSongsIdAndSlugGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
