/* tslint:disable */
/* eslint-disable */
/**
 * Relisten API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    BooleanResponseEnvelope,
    BooleanResponseEnvelopeFromJSON,
    BooleanResponseEnvelopeToJSON,
    TourWithShowCount,
    TourWithShowCountFromJSON,
    TourWithShowCountToJSON,
    TourWithShows,
    TourWithShowsFromJSON,
    TourWithShowsToJSON,
} from '../models';

export interface ApiV2ArtistsArtistIdOrSlugToursGetRequest {
    artistIdOrSlug: string;
}

export interface ApiV2ArtistsArtistIdOrSlugToursIdAndSlugGetRequest {
    artistIdOrSlug: string;
    idAndSlug: string;
}

/**
 * 
 */
export class ToursApi extends runtime.BaseAPI {

    /**
     */
    async apiV2ArtistsArtistIdOrSlugToursGetRaw(requestParameters: ApiV2ArtistsArtistIdOrSlugToursGetRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<TourWithShowCount>>> {
        if (requestParameters.artistIdOrSlug === null || requestParameters.artistIdOrSlug === undefined) {
            throw new runtime.RequiredError('artistIdOrSlug','Required parameter requestParameters.artistIdOrSlug was null or undefined when calling apiV2ArtistsArtistIdOrSlugToursGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v2/artists/{artistIdOrSlug}/tours`.replace(`{${"artistIdOrSlug"}}`, encodeURIComponent(String(requestParameters.artistIdOrSlug))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TourWithShowCountFromJSON));
    }

    /**
     */
    async apiV2ArtistsArtistIdOrSlugToursGet(requestParameters: ApiV2ArtistsArtistIdOrSlugToursGetRequest, initOverrides?: RequestInit): Promise<Array<TourWithShowCount>> {
        const response = await this.apiV2ArtistsArtistIdOrSlugToursGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiV2ArtistsArtistIdOrSlugToursIdAndSlugGetRaw(requestParameters: ApiV2ArtistsArtistIdOrSlugToursIdAndSlugGetRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<TourWithShows>> {
        if (requestParameters.artistIdOrSlug === null || requestParameters.artistIdOrSlug === undefined) {
            throw new runtime.RequiredError('artistIdOrSlug','Required parameter requestParameters.artistIdOrSlug was null or undefined when calling apiV2ArtistsArtistIdOrSlugToursIdAndSlugGet.');
        }

        if (requestParameters.idAndSlug === null || requestParameters.idAndSlug === undefined) {
            throw new runtime.RequiredError('idAndSlug','Required parameter requestParameters.idAndSlug was null or undefined when calling apiV2ArtistsArtistIdOrSlugToursIdAndSlugGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v2/artists/{artistIdOrSlug}/tours/{idAndSlug}`.replace(`{${"artistIdOrSlug"}}`, encodeURIComponent(String(requestParameters.artistIdOrSlug))).replace(`{${"idAndSlug"}}`, encodeURIComponent(String(requestParameters.idAndSlug))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TourWithShowsFromJSON(jsonValue));
    }

    /**
     */
    async apiV2ArtistsArtistIdOrSlugToursIdAndSlugGet(requestParameters: ApiV2ArtistsArtistIdOrSlugToursIdAndSlugGetRequest, initOverrides?: RequestInit): Promise<TourWithShows> {
        const response = await this.apiV2ArtistsArtistIdOrSlugToursIdAndSlugGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
