// tslint:disable
/**
 * Relisten API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { HttpMethods, QueryConfig, ResponseBody, ResponseText } from 'redux-query';
import * as runtime from '../runtime';
import {
    BooleanResponseEnvelope,
    BooleanResponseEnvelopeFromJSON,
    BooleanResponseEnvelopeToJSON,
    VenueWithShowCount,
    VenueWithShowCountFromJSON,
    VenueWithShowCountToJSON,
    VenueWithShows,
    VenueWithShowsFromJSON,
    VenueWithShowsToJSON,
} from '../models';

export interface ApiV2ArtistsArtistIdOrSlugVenuesGetRequest {
    artistIdOrSlug: string;
}

export interface ApiV2ArtistsArtistIdOrSlugVenuesIdAndSlugGetRequest {
    artistIdOrSlug: string;
    idAndSlug: string;
}


/**
 */
function apiV2ArtistsArtistIdOrSlugVenuesGetRaw<T>(requestParameters: ApiV2ArtistsArtistIdOrSlugVenuesGetRequest, requestConfig: runtime.TypedQueryConfig<T, Array<VenueWithShowCount>> = {}): QueryConfig<T> {
    if (requestParameters.artistIdOrSlug === null || requestParameters.artistIdOrSlug === undefined) {
        throw new runtime.RequiredError('artistIdOrSlug','Required parameter requestParameters.artistIdOrSlug was null or undefined when calling apiV2ArtistsArtistIdOrSlugVenuesGet.');
    }

    let queryParameters = null;


    const headerParameters : runtime.HttpHeaders = {};


    const { meta = {} } = requestConfig;

    const config: QueryConfig<T> = {
        url: `${runtime.Configuration.basePath}/api/v2/artists/{artistIdOrSlug}/venues`.replace(`{${"artistIdOrSlug"}}`, encodeURIComponent(String(requestParameters.artistIdOrSlug))),
        meta,
        update: requestConfig.update,
        queryKey: requestConfig.queryKey,
        optimisticUpdate: requestConfig.optimisticUpdate,
        force: requestConfig.force,
        rollback: requestConfig.rollback,
        options: {
            method: 'GET',
            headers: headerParameters,
        },
        body: queryParameters,
    };

    const { transform: requestTransform } = requestConfig;
    if (requestTransform) {
        config.transform = (body: ResponseBody, text: ResponseBody) => requestTransform(body.map(VenueWithShowCountFromJSON), text);
    }

    return config;
}

/**
*/
export function apiV2ArtistsArtistIdOrSlugVenuesGet<T>(requestParameters: ApiV2ArtistsArtistIdOrSlugVenuesGetRequest, requestConfig?: runtime.TypedQueryConfig<T, Array<VenueWithShowCount>>): QueryConfig<T> {
    return apiV2ArtistsArtistIdOrSlugVenuesGetRaw(requestParameters, requestConfig);
}

/**
 */
function apiV2ArtistsArtistIdOrSlugVenuesIdAndSlugGetRaw<T>(requestParameters: ApiV2ArtistsArtistIdOrSlugVenuesIdAndSlugGetRequest, requestConfig: runtime.TypedQueryConfig<T, VenueWithShows> = {}): QueryConfig<T> {
    if (requestParameters.artistIdOrSlug === null || requestParameters.artistIdOrSlug === undefined) {
        throw new runtime.RequiredError('artistIdOrSlug','Required parameter requestParameters.artistIdOrSlug was null or undefined when calling apiV2ArtistsArtistIdOrSlugVenuesIdAndSlugGet.');
    }

    if (requestParameters.idAndSlug === null || requestParameters.idAndSlug === undefined) {
        throw new runtime.RequiredError('idAndSlug','Required parameter requestParameters.idAndSlug was null or undefined when calling apiV2ArtistsArtistIdOrSlugVenuesIdAndSlugGet.');
    }

    let queryParameters = null;


    const headerParameters : runtime.HttpHeaders = {};


    const { meta = {} } = requestConfig;

    const config: QueryConfig<T> = {
        url: `${runtime.Configuration.basePath}/api/v2/artists/{artistIdOrSlug}/venues/{idAndSlug}`.replace(`{${"artistIdOrSlug"}}`, encodeURIComponent(String(requestParameters.artistIdOrSlug))).replace(`{${"idAndSlug"}}`, encodeURIComponent(String(requestParameters.idAndSlug))),
        meta,
        update: requestConfig.update,
        queryKey: requestConfig.queryKey,
        optimisticUpdate: requestConfig.optimisticUpdate,
        force: requestConfig.force,
        rollback: requestConfig.rollback,
        options: {
            method: 'GET',
            headers: headerParameters,
        },
        body: queryParameters,
    };

    const { transform: requestTransform } = requestConfig;
    if (requestTransform) {
        config.transform = (body: ResponseBody, text: ResponseBody) => requestTransform(VenueWithShowsFromJSON(body), text);
    }

    return config;
}

/**
*/
export function apiV2ArtistsArtistIdOrSlugVenuesIdAndSlugGet<T>(requestParameters: ApiV2ArtistsArtistIdOrSlugVenuesIdAndSlugGetRequest, requestConfig?: runtime.TypedQueryConfig<T, VenueWithShows>): QueryConfig<T> {
    return apiV2ArtistsArtistIdOrSlugVenuesIdAndSlugGetRaw(requestParameters, requestConfig);
}

